### ISSUE TITLE
issues if language is not English

### ISSUE THREAD

**Issue by githubertus** [lianglee/MenuBuilder#1]
Starting with my language set to English
I added a new menu entry to admin backend right side usermanager
![menubuilder1](https://user-images.githubusercontent.com/9904364/70390464-952c8600-19cb-11ea-8e4e-7e19a4e278d8.png)
and in fact this was added correctly like
![menubuilder2](https://user-images.githubusercontent.com/9904364/70390494-d886f480-19cb-11ea-9f47-9194705828db.png)
but after switching to German, the new entry is no more part of the usermanager
![menubuilder3](https://user-images.githubusercontent.com/9904364/70390520-108e3780-19cc-11ea-928e-f16fcdc452d3.png)
instead an additional menu is shown with the entry
![menubuilder4](https://user-images.githubusercontent.com/9904364/70390554-3fa4a900-19cc-11ea-9593-2146d9299400.png)

**Comment by lianglee** [comment]
Will Check in few moments

**Comment by lianglee** [comment]
Fixed
